---
- hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Gather VM facts
      vmware_guest_facts:
        hostname: 172.18.0.13
        datacenter: LAB
        username: administrator@vsphere.local
        password: !LpdlrK57
        validate_certs: no
        name: 49a56cb0-3206-11e7-8820-000c29157e9f
    delegate_to: localhost
    register: facts
